#!/bin/bash

# Plays aquarium video stream as screensaver
# --------------------------------------------------------------------------------------------------------------

mpv --volume=0 --no-osc --fs --video-zoom=0.115 https://www.youtube.com/watch?v=9Ej-0VRWmI8&t=218&t=212s
