#!/bin/bash
#
# Adds an url for my gamechill script
#  --------------------------------------------------------------------------------------------------------------
touch ~/permanent/public/media/gamechill-urls/"$1" && echo $2 > ~/permanent/public/media/gamechill-urls/"$1"
