#!/bin/bash
# 
#  
#  --------------------------------------------------------------------------------------------------------------

while read l; do if [[ $(grep "$l" archQe.pacman) != "" ]]; then a=0; else  echo "$l"; fi; done <tmp.tmp
