#!/bin/sh

config=~/permanent/private/keys/notes-synced.login
mail="fabian3@fabian.fabian"
password="fabianfabian"
cache=~/permanent/cache/notes-synced.tmp

while [ ! $# -eq 0 ]
do
	case "$1" in
		-d | --default)
			echo "using notes with default script at $config"
			$mail="fabian3@fabian.fabian"
			$password="fabianfabian"
		;;
		-r | --read)
			echo "using read-only mode"
		;;
		-p | --password)
			$password=$2
		;;
		-m | --mail)
			$mail=$2
		;;        
        esac
        shift
done

data=$( \
	jq -n \
	--arg em "$mail" \
	--arg pw "$password" \
	'{email:$em, password:$pw}' \
)

token=$( \
	curl \
	--header "Content-Type: application/json" \
	--request POST \
	--data "$( \
		jq -n \
	        --arg em "$mail" \
	        --arg pw "$password" \
	        '{email:$em, password:$pw}' \
	)" \
	"https://europe-west1-notes-synced.cloudfunctions.net/api/signin" \
	| jq -r '.token')
	
notes=$( \
	curl \
	--header "Content-Type: application/json" \
	--header "Authorization: Bearer $token" \
	--request POST \
	"https://europe-west1-notes-synced.cloudfunctions.net/api/pulldata" \
)

echo; echo recieved: $notes; echo

rm $cache & touch $cache && \
echo $(node -e "console.log('$notes'.replace(/[\\\]/g, '').replace(/\"\"\"/g, '\"'))") > $cache && \
echo prettyfied: $(cat $cache) && nano $cache && \
curl \
	--header "Content-Type: application/json" \
	--header "Authorization: Bearer $token" \
	--request POST \
	--data "$( \
		jq -n \
		--arg n "$(cat $cache)" \
		'{notes:$n}' \
	)" \
    "https://europe-west1-notes-synced.cloudfunctions.net/api/update" 
echo
