#!/bin/bash

# Plays the twitch stream of a given creator using his/her handle.
# --------------------------------------------------------------------------------------------------------------
# Usage: ./twitch streamername
# --------------------------------------------------------------------------------------------------------------


mpv --geometry=30% https://www.twitch.tv/$1;
