#!/bin/bash

# Plays the twitch stream of a given creator using his/her handle.
# --------------------------------------------------------------------------------------------------------------
# Usage: ./twitch streamername
# --------------------------------------------------------------------------------------------------------------


mpv --no-osc https://www.twitch.tv/$1;
