#!/bin/bash
# 
#  
#  --------------------------------------------------------------------------------------------------------------

notify-send \
	-h string:x-canonical-private-synchronous:anything \
	-a "Big-Brain-Volume-Script" \
	"$(echo -e \
		"Combined: $( \
			pactl list sinks \
			| grep -A 7 'Name: combined' \
			| tail -n 1 \
			| sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
		)%\nHDMI: $( \
			pactl list sinks \
                        | grep -A 7 'Name: alsa_output.pci-0000_03_00.1.hdmi-stereo' \
                        | tail -n 1 \
                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
		 )%\nBluetooth Headphones: $( \
                        pactl list sinks \
                        | grep -A 7 'Name: bluez_sink.17_50_01_A0_01_16.a2dp_sink' \
                        | tail -n 1 \
                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
		)%\n3.5mm Jack (Front): $( \
                        pactl list sinks \
                        | grep -A 7 'Name: alsa_output.pci-0000_00_1f.3.analog-stereo' \
                        | tail -n 1 \
                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
                )%\n3.5mm Jack (Back): $( \
                        pactl list sinks \
                        | grep -A 7 'Name: alsa_output.platform-snd_aloop.0.analog-stereo' \
                        | tail -n 1 \
                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
                )%" \
	)"
