#!/bin/bash
# 
#  
#  --------------------------------------------------------------------------------------------------------------

# OLD VERSION
#
# notify-send \
#	-h string:x-canonical-private-synchronous:anything \
#	-a "Big-Brain-Volume-Script" \
#	"$(echo -e \
#		"Combined: . . . . . . . . . . . . . $( \
#			pactl list sinks \
#			| grep -A 7 'Name: combined' \
#			| tail -n 1 \
#			| sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
#		)%\nTV: . . . . . . . . . . . . . . . . $( \
#			pactl list sinks \
#                        | grep -A 7 'Name: alsa_output.pci-0000_03_00.1.hdmi-stereo' \
#                        | tail -n 1 \
#                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
#		 )%\nBluetooth Headphones: . . . . . . . $( \
#                        pactl list sinks \
#                        | grep -A 7 'Name: bluez_sink' \
#                        | tail -n 1 \
#                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
#		)%\n3.5mm Jack (Back):  . . . . . . . . $( \
#                        pactl list sinks \
#                        | grep -A 7 'Name: alsa_output.pci-0000_00_1f.3.analog-stereo' \
#                        | tail -n 1 \
#                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
#                )%\n3.5mm Jack (Front): . . . . . . . . $( \
#                        pactl list sinks \
#                        | grep -A 7 'Name: alsa_output.platform-snd_aloop.0.analog-stereo' \
#                        | tail -n 1 \
#                        | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
#                )%" \
#	)"

# NEW VERSION
#

sink() { # get sink main volume by Name prop
    echo $( \
        pactl list sinks \
            | grep -A 7 "Name: $1" \
            | tail -n 1 \
            | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' \
    )
}

space() { # echo n=$1 spaces
    echo "$(dd if=~/permanent/public/path-scripts/req/space bs=$1 count=1)"
}

submit() {
    notify-send \
	-u normal \
	-h string:x-canonical-private-synchronous:anything \
	-a ":░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░" \
	"$1"
}

COM=$(sink "combined")
TV=$(sink "alsa_output.pci-0000_03_00.1.hdmi-stereo")
B_HP=$(sink "bluez_sink")
BA=$(sink "alsa_output.pci-0000_00_1f.3.analog-stereo")
FR=$(sink "alsa_output.platform-snd_aloop.0.analog-stereo")

LEN=$((40-$(echo "$COM$TV$B_HP$BA$FR" | wc -c))) # the amount of characters that can be used without a linebreak

if [ -z "$TV" ]
then
    if [ -z "$B_HP" ]
    then
        submit "$COM:$(space $(($LEN-7)))B:$BA | F:$FR"
        
    else                                                 # -11 instead of -12 to round up
        submit "$COM:$(space $((($LEN-12)/2)))B-HP:$B_HP$(space $((($LEN-11)/2)))B:$BA | F:$FR"
    fi
else
   if [ -z "$B_HP" ]
    then
        submit "$COM:$(space $((($LEN-10)/2)))TV:$TV$(space $((($LEN-9)/2)))B:$BA | F:$FR"
        
    else
        submit "$COM:$(space $((($LEN-18)/2)))TV:$TV | B-HP:$B_HP$(space $((($LEN-17)/2)))B:$BA | F:$FR"
    fi
fi
