#!/bin/bash

# Plays a Youtube video by handle using mpv.
# --------------------------------------------------------------------------------------------------------------
# Usage: ./ytdl-play Title of the video
# --------------------------------------------------------------------------------------------------------------


echo "$@" > ~/permanent/cache/tmp.ytdl-play; 
~/permanent/public/path-scripts/getUrl ~/permanent/cache/tmp.ytdl-play;
mpv --geometry=30% "$(< ~/permanent/cache/tmp.ytdl-play)" && rm ~/permanent/cache/tmp.ytdl-play;
