#!/bin/bash

# Downloads a Youtube video by handle.
# --------------------------------------------------------------------------------------------------------------
# Usage: ./ytdl-use-name Title of the video
# --------------------------------------------------------------------------------------------------------------


echo "$@" > tmp.ytdl-use-name;  
/home/desjardins/permanent/public/path-scripts/getUrl tmp.ytdl-use-name;
youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4'  "$(cat tmp.ytdl-use-name)";
rm tmp.ytdl-use-name;
