#!/bin/bash

# Plays a Youtube video by handle using mpv.
# --------------------------------------------------------------------------------------------------------------
# Usage: ./ytdl-play Title of the video
# --------------------------------------------------------------------------------------------------------------

cache=~/permanent/cache/tmp.ytdl-play
getUrl=~/permanent/public/path-scripts/getUrl

echo "$@" > $cache && \
$getUrl $cache && \
echo $(cat $cache) && \
mpv --no-osc "$(cat $cache)" && rm $cache
