#!/bin/bash

# Plays a Youtube video by handle using mpv.
# --------------------------------------------------------------------------------------------------------------
# Usage: ./ytdl-play Title of the video
# --------------------------------------------------------------------------------------------------------------


echo "$@" > tmp.ytdl-play; 
~/permanent/public/path-scripts/getUrl tmp.ytdl-play;
mpv "$(< tmp.ytdl-play)" & rm tmp.ytdl-play;
