#!/bin/sh  -> formatting
#
# i3 config file (v4)
#

set $mod Mod1
set $win Mod4
set $media ~/permanent/public/media
set $bash ~/permanent/public/bash
set $path-scripts ~/permanent/public/path-scripts
set $dunstrc ~/.config/dunst/dunstrc
set $compton-conf ~/.config/compton/config
set $i3 ~/.config/i3

set $ws1 "1" 
set $ws2 "2" 
set $ws3 "3" 
set $ws4 "4" 
set $ws5 "5" 
set $ws6 "6" 
set $ws7 "7" 
set $ws8 "8" 
set $ws9 "9" 
set $ws10 "10"

gaps inner 5 
#border_radius 7
default_border pixel 0

#testing
default_floating_border pixel 0
#font pango:DejaVu Sans Mono 8 1
font pango:monospace 10
floating_modifier $mod

for_window [title="Volume Control"] border pixel 0
for_window [title="PAYDAY 2"] border pixel 0
for_window [title="Volume Control"] floating disable
for_window [title="masterduel"] border pixel 0
for_window [class="Steam"] border pixel 0
for_window [class="gta5.exe"] border pixel 0
for_window [class="firefox"] border pixel 0
for_window [class="Timeshift-gtk"] border pixel 0
for_window [class="Robocraft.x86_64"] border pixel 0
for_window [class="polkit-kde-authentication-agent-1"] border pixel 0
for_window [class="Zenity"] border pixel 0

workspace 1 output DisplayPort-2
workspace 2 output DisplayPort-1
workspace 3 output HDMI-A-0

exec --no-startup-id \
	xrandr --output DisplayPort-2 --auto --left-of DisplayPort-1 \
	&& xrandr --output HDMI-A-0 --auto --left-of DisplayPort-2 \
	&& feh --bg-fill $i3/bg.jpg --bg-fill $i3/bg.jpg --bg-fill $i3/bg.jpg \
	&& polybar -r example \
	&  XDG_CURRENT_DESKTOP=13 mailspring -b \
	&  XDG_CURRENT_DESKTOP=13 discord --start-minimized \
	&  blueman-applet \
	&  nm-applet \
	&  xset r rate 200 45 \
	&  dunst -conf ~/.config/dunst/dunstrc \
	&  /usr/lib/polkit-kde-authentication-agent-1 \
	&  pactl set-sink-volume alsa_output.pci-0000_09_00.4.analog-stereo 100% \
	&  pactl set-default-sink combined \
	&  kdeconnect-cli --refresh \
	&  autotiling \
	&  picom --config ~/.config/picom/conf
	
bindsym $mod+e \
	move left

bindsym $mod+r \
	move right

bindsym $mod+t \
	move up

bindsym $mod+v \
	move down

bindsym $mod+f \
	fullscreen toggle

bindsym $mod+space \
	floating toggle

bindsym $win+r \
	exec i3-msg restart & killall polybar; polybar example & autotiling

bindsym $mod+s \
	exec --no-startup-id xset r rate 200 45

bindsym $mod+d \
	exec --no-startup-id rofi -no-lazy-grab -show drun -modi drun -theme $i3/applauncher.rasi 

bindsym XF86AudioRaiseVolume \
	exec --no-startup-id pactl set-sink-volume combined +5% \
	&& $refresh_i3status

bindsym XF86AudioLowerVolume \
	exec --no-startup-id pactl set-sink-volume combined -5% \
	&& $refresh_i3status

bindsym $mod+Return \
	exec --no-startup-id gnome-terminal

bindsym $mod+q \
	kill

bindsym $mod+1 workspace number $ws1 
bindsym $mod+2 workspace number $ws2 
bindsym $mod+3 workspace number $ws3 
bindsym $mod+4 workspace number $ws4 
bindsym $mod+5 workspace number $ws5 
bindsym $mod+6 workspace number $ws6 
bindsym $mod+7 workspace number $ws7 
bindsym $mod+8 workspace number $ws8 
bindsym $mod+9 workspace number $ws9 
bindsym $mod+0 workspace number $ws10

bindsym $win+1 move container to workspace number $ws1 
bindsym $win+2 move container to workspace number $ws2 
bindsym $win+3 move container to workspace number $ws3 
bindsym $win+4 move container to workspace number $ws4 
bindsym $win+5 move container to workspace number $ws5 
bindsym $win+6 move container to workspace number $ws6 
bindsym $win+7 move container to workspace number $ws7 
bindsym $win+8 move container to workspace number $ws8 
bindsym $win+9 move container to workspace number $ws9 
bindsym $win+0 move container to workspace number $ws10
