#!/bin/sh  -> for VSCode
#
# i3 config file (v4)
#

set $mod Mod1
set $win Mod4
set $media ~/permanent/public/media
set $bash ~/permanent/public/bash
set $path-scripts ~/permanent/public/path-scripts
set $dunstrc ~/.config/dunst/dunstrc
set $compton-conf ~/.config/compton/config
set $i3 ~/.config/i3

set $ws1 "1" 
set $ws2 "2" 
set $ws3 "3" 
set $ws4 "4" 
set $ws5 "5" 
set $ws6 "6" 
set $ws7 "7" 
set $ws8 "8" 
set $ws9 "9" 
set $ws10 "10"

gaps inner 15 
border_radius 4
default_border pixel 0
font pango:monospace 10 #font pango:DejaVu Sans Mono 8
floating_modifier $mod

exec --no-startup-id \
	~/xrandr-do \
	&& feh --bg-fill $media/bg-2.jpg --bg-fill $media/bg-1.jpg --bg-fill $media/bg-3.jpg \
	&& polybar example \
	&  mailspring -b \
	&  discord --start-minimized \
	&  blueman-applet \
	&  nm-applet \
	&  xset r rate 200 45 \
	&  dunst -conf ~/.config/dunst/dunstrc \
	&  compton --config ~/permanent/public/compton.conf \
	&  /usr/lib/polkit-kde-authentication-agent-1 \
	&  pactl set-sink-volume alsa_output.pci-0000_00_1f.3.analog-stereo 100% \
	&  kdeconnect-cli --refresh \
	&  autotiling
#	&  xss-lock --transfer-sleep-lock -- i3lock --nofork \
#	&  nm-applet
	
bindsym $mod+e \
	move left

bindsym $mod+r \
	move right

bindsym $mod+t \
	move up

bindsym $mod+v \
	move down


bindsym $mod+k \
	focus left 

bindsym $mod+m \
	focus down 

bindsym $mod+i \
	focus up 

bindsym $mod+l \
	focus right


bindsym $mod+h \
	split h

bindsym $mod+g \
	split v


bindsym $mod+f \
	fullscreen toggle

bindsym $mod+space \
	floating toggle

# change focus between tiling / floating windows
bindsym $mod+Shift+space \
	focus mode_toggle

# focus the parent container
bindsym $mod+a \
	focus parent

bindsym $win+r \
	exec i3-msg restart


bindsym $mod+s \
	exec --no-startup-id xset r rate 200 45

bindsym $mod+d \
	exec --no-startup-id rofi -no-lazy-grab -show drun -modi drun -theme $i3/applauncher.rasi 

bindsym XF86AudioRaiseVolume \
	exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +5% \
	&& $refresh_i3status \
#	&& $path-scripts/volume-notify

bindsym XF86AudioLowerVolume \
	exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -5% \
	&& $refresh_i3status \
#	&& $path-scripts/volume-notify

bindsym $mod+Return \
	exec --no-startup-id gnome-terminal

bindsym $mod+q \
	kill

bindsym $mod+w \
	mode "resize"

bindsym $win+m \
	mode "mouse"

bindsym $mod+1 workspace number $ws1 
bindsym $mod+2 workspace number $ws2 
bindsym $mod+3 workspace number $ws3 
bindsym $mod+4 workspace number $ws4 
bindsym $mod+5 workspace number $ws5 
bindsym $mod+6 workspace number $ws6 
bindsym $mod+7 workspace number $ws7 
bindsym $mod+8 workspace number $ws8 
bindsym $mod+9 workspace number $ws9 
bindsym $mod+0 workspace number $ws10

bindsym $win+1 move container to workspace number $ws1 
bindsym $win+2 move container to workspace number $ws2 
bindsym $win+3 move container to workspace number $ws3 
bindsym $win+4 move container to workspace number $ws4 
bindsym $win+5 move container to workspace number $ws5 
bindsym $win+6 move container to workspace number $ws6 
bindsym $win+7 move container to workspace number $ws7 
bindsym $win+8 move container to workspace number $ws8 
bindsym $win+9 move container to workspace number $ws9 
bindsym $win+0 move container to workspace number $ws10

mode "resize" {
        bindsym k \
            resize shrink width 10 px or 10 ppt 
        
        bindsym i \
            resize grow height 10 px or 10 ppt 
        
        bindsym m \
            resize shrink height 10 px or 10 ppt 
        
        bindsym l \
            resize grow width 10 px or 10 ppt

            
        bindsym Left \
            resize shrink width 10 px or 10 ppt 
        
        bindsym Down \
            resize grow height 10 px or 10 ppt 
        
        bindsym Up \
            resize shrink height 10 px or 10 ppt 
        
        bindsym Right \
            resize grow width 10 px or 10 ppt

            
        bindsym Return \
            mode "default" 
        
        bindsym Escape \
            mode "default" 
        
        bindsym $mod+r \
            mode "default"
}

mode "mouse" {
    # modified: https://www.reddit.com/r/i3wm/comments/3btki2/use_the_mouse_cursor_from_the_keyboard/

    set $spd 20

    bindsym d \
        exec xdotool mousemove_relative -- -$spd 0

    bindsym m \
        exec xdotool mousemove_relative 0 $spd

    bindsym i \
        exec xdotool mousemove_relative -- 0 -$spd

    bindsym f \
        exec xdotool mousemove_relative $spd 0

        
    # Left Click
    bindsym g \
        exec xdotool click 1

    # Middle Click
    bindsym h \
        exec xdotool click 2

    # Right Click
    bindsym j \
        exec xdotool click 3

    # Left Click-and-drag
    bindsym Shift+g \
        exec xdotool mousedown 1

    # Middle Click-and-drag 
    bindsym Shift+h \
        exec xdotool mousedown 2

    # Right Click-and-drag
    bindsym Shift+j \
        exec xdotool mousedown 3

    # Left Drag release
    bindsym $mod+g \
        exec xdotool mouseup 1

    # Middle Drag release
    bindsym $mod+h \
        exec xdotool mouseup 2

    # Right Drag release
    bindsym $mod+j \
        exec xdotool mouseup 3

        
    # return
    bindsym Escape \
        mode "default"

    bindsym $win+m \
        mode "default"
}
