#!/bin/bash

# the relative path to use for all scripts started by ethmine

cd /home/desjardins/permanent/public/path-scripts/root

state="../../../cache/ethmine-state"
sLauncher="./supervisor-launcher"
ethmine="./ethmine"

trap ctrl-c INT

function ctrl-c() {
	$ethmine -k
}

# --kill | -k
# kill ethminer & supervisor and update state
# only terminate if ethminer has terminated

if [[ $@ == *--kill* || $@ == *-k* ]]; then
	echo "0" > $state && killall eth-supervisor
	
	while ! [[ $(pidof ethminer) == "" ]]; do
		echo "ethminer did not react to ctrl-c. Killing it manually..."
		killall ethminer
		sleep 1s
	done 

	echo "terminated successfully" && exit
fi

# --start | -s
# start the supervisor, if not already running
# if ethminer exits, restart it if the state is 1 (unwanted exit),
# reset the state and terminate

if [[ $@ == *--start* || $@ == *-s* ]]; then
	if [[ $(pgrep eth-supervisor) == "" ]]; then
		sudo $sLauncher &	
	fi

	while true; do
		if [[ "$(cat $state)" == "0" ]]; then
			echo "1" > $state
			break
		fi
		ethminer -P stratum://0x285187DE0E1067d1e25874691E40bE4A1d1980EA@eu1.ethermine.org:4444
	done
else
	# unrecognized or no option

	echo
	echo "You specified no action when launching this script. What do you want to do?"
	echo
	echo "options:"
	echo
	echo "-s | --start"
	echo "-k | --kill"
	echo
fi