#!/bin/bash

# border is the rashrate below which the algorithm will restart
# ethminer, to counter bugs like the all-shares-reject-bug

border=20000000
ethmine="./ethmine"

# wait for the hasrate to rise, dont terminate while starting

sleep 60m \
&& while true; do

	# if ethminer isnt active anymore, terminate
	if [[ $(pidof ethminer) == "" ]]; then
		break
	fi
	
	# get the 60min-average hashrate from ethermine.org API
	hashrate=$(
		curl api.ethermine.org/miner/0x285187DE0E1067d1e25874691E40bE4A1d1980EA/workers \
		| jq '.data' \
		| jq '.[].currentHashrate'
	)

	# if hasrate lower than $border, restart
	if (( $(echo "$border > $hashrate" | bc -l) )); then
		sudo $ethmine -k \
		&& sleep 15s \
		&& sudo $ethmine -s
	fi

	# repeat every 10m
	sleep 10m
done
