#!/bin/bash

pid="./eth-supervisor"
supervisor="./supervisor"

# supervisor-launcher starts supervisor with a symlink, 
# so it can be found with pgrep

if [[ $(pgrep "eth-supervisor") == "" ]]; then

	# remove existsing symlink
	rm -f "$pid"

	# create new one
	ln -s "$supervisor" "$pid"

	# start the execution of the supervisor
	exec "$pid"
fi