#!/bin/sh
# base version was naughtily copied from here:
# https://github.com/EdenQwQ/dots/blob/master/.config/picom.conf

#################################
#             Shadows           #
#################################


shadow = true;
shadow-radius = 20
# shadow-opacity = .75

shadow-offset-x = -7;
shadow-offset-y = -7;

shadow-color = "#000000"

# Specify a list of conditions of windows that should have no shadow.
#
# examples:
#   shadow-exclude = "n:e:Notification";
#
# shadow-exclude = []
# shadow-exclude = [
#   "name = 'Notification'",
#   "class_g = 'Conky'",
#   "class_g ?= 'Notify-osd'",
#   "class_g = 'Cairo-clock'",
#   "_GTK_FRAME_EXTENTS@:c"
# ];

# Specify a list of conditions of windows that should have no shadow painted over, such as a dock window.
# clip-shadow-above = []

# Specify a X geometry that describes the region in which shadow should not
# be painted in, such as a dock window region. Use
#    shadow-exclude-reg = "x10+0+0"
# for example, if the 10 pixels on the bottom of the screen should not have shadows painted on.
#
# shadow-exclude-reg = ""

# Crop shadow of a window fully on a particular Xinerama screen to the screen.
# xinerama-shadow-crop = false


#################################
#           Fading              #
#################################

fading = false;
# fade-exclude = []
no-fading-destroyed-argb = false

#################################
#   Transparency / Opacity      #
#################################


inactive-opacity = 1
inactive-opacity-override = true
active-opacity = 1

# Dim inactive windows. (0.0 - 1.0, defaults to 0.0)
inactive-dim = 0.05

# focus-exclude = []

opacity-rule = [ 
    "100:_NET_WM_STATE@:32a = '_NET_WM_STATE_FULLSCREEN'", 
    "100:class_g = 'VirtualBox Machine'",
    "100:class_g = 'cemu.exe'",
    "100:class_g = 'Dunst'",
	"100:class_g = 'scrcpy'",
    "90:class_g = 'pavucontrol-qt'",
    "90:class_g = 'gnome-terminal-server' && focused",
    "90:class_g = 'spotify' && focused"
];


#################################
#           Corners             #
#################################

corner-radius = 7

# Exclude conditions for rounded corners.
rounded-corners-exclude = [
  # "window_type = 'dock'",
  # "window_type = 'desktop'"
];


#################################
#     Background-Blurring       #
#################################

# Parameters for background blurring, see the *BLUR* section for more information.
# blur-method =
# blur-size = 12
#
# blur-deviation = false
#
# blur-strength = 5

# Blur background of semi-transparent / ARGB windows.
# Bad in performance, with driver-dependent behavior.
# The name of the switch may change without prior notifications.
#
# blur-background = false

# Blur background of windows when the window frame is not opaque.
# Implies:
#    blur-background
# Bad in performance, with driver-dependent behavior. The name may change.
#
# blur-background-frame = false


# Use fixed blur strength rather than adjusting according to window opacity.
# blur-background-fixed = false


# Specify the blur convolution kernel, with the following format:
# example:
#   blur-kern = "5,5,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1";
#
# blur-kern = ""
blur-kern = "3x3box";


# Exclude conditions for background blur.
# blur-background-exclude = []
# blur-background-exclude = [
#   "window_type = 'dock'",
#   "window_type = 'desktop'",
#   "_GTK_FRAME_EXTENTS@:c"
# ];


#################################
#          Animations           #
#################################
animations = true
# `auto`, `none`, `fly-in`, `zoom`, `slide-down`, `slide-up`, `slide-left`, `slide-right` `slide-in`, `slide-out`
animation-for-transient-window = "zoom"
animation-for-open-window = "zoom"
animation-for-unmap-window = "zoom"
# animation-stiffness = 350
animation-dampening = 20
# animation-window-mass = 0.5
# animation-delta = 8
animation-clamping = false


#################################
#       General Settings        #
#################################

daemon = true
experimental-backends = true
backend = "glx"
vsync = true;
mark-wmwin-focused = true;
mark-ovredir-focused = false
detect-rounded-corners = true;
detect-client-opacity = false
refresh-rate = 60
detect-transient = true;
detect-client-leader = false
resize-damage = 1
glx-no-stencil = true
glx-no-rebind-pixmap = true
use-damage = false;
xrender-sync-fence = true
force-win-blend = true
transparent-clipping = false
log-level = "info";

# 'WINDOW_TYPE' is one of the 15 window types defined in EWMH standard:
#     "unknown", "desktop", "dock", "toolbar", "menu", "utility",
#     "splash", "dialog", "normal", "dropdown_menu", "popup_menu",
#     "tooltip", "notification", "combo", and "dnd".
#
# Following per window-type options are available: ::
#
#   fade, shadow:::
#     Controls window-type-specific shadow and fade settings.
#
#   opacity:::
#     Controls default opacity of the window type.
#
#   focus:::
#     Controls whether the window of this type is to be always considered focused.
#     (By default, all window types except "normal" and "dialog" has this on.)
#
#   full-shadow:::
#     Controls whether shadow is drawn under the parts of the window that you
#     normally won't be able to see. Useful when the window has parts of it
#     transparent, and you want shadows in those areas.
#
#   clip-shadow-above:::
#     Controls wether shadows that would have been drawn above the window should
#     be clipped. Useful for dock windows that should have no shadow painted on top.
#
#   redir-ignore:::
#     Controls whether this type of windows should cause screen to become
#     redirected again after been unredirected. If you have unredir-if-possible
#     set, and doesn't want certain window to cause unnecessary screen redirection,
#     you can set this to `true`.
#
wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = true; };
  dock = { shadow = true; clip-shadow-above = true; }
  dnd = { shadow = true; }
  popup_menu = { opacity = 0.95; }
  dropdown_menu = { opacity = 0.95; }
};
