#!/bin/bash

# gets the volume of sink 4, stolen from https://unix.stackexchange.com/questions/132230/read-out-pulseaudio-volume-from-commandline-i-want-pactl-get-sink-volume
# --------------------------------------------------------------------------------------------------------------
pactl list sinks | grep '^[[:space:]]Volume:' |     head -n $(( $SINK + 4 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
